# Working with Raster Bands

## Preparing Your Workspace

### Option 1: (recommended) Run in Google Colab
[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/kevinlacaille/presentations/blob/main/scipy2024/1_rasters.ipynb)

### Option 2: Run local Jupyter instance
You can also choose to open this Notebook in your own local Jupyter instance.

**Prerequisites**

- Install: rasterio
- Download data

In [ ]:
!pip install rasterio
!wget https://raw.githubusercontent.com/kevinlacaille/presentations/main/scipy2024/data/presentation/8928dec4ddbffff/DJI_0876.JPG

In [ ]:
import rasterio

Either use path defined in Google Colab or path relative to this notebook in the repo.

In [ ]:
import os

# Define both potential file paths
image_path = "/content/DJI_0876.JPG" if os.path.exists(
    "/content/DJI_0876.JPG"
) else "data/presentation/8928dec4ddbffff/DJI_0876.JPG"

### Examining Metadata

Open a geospatial image using Rasterio and print its metadata, the number of bands, projection information, and spatial bounds.


In [ ]:
# Open the image
with rasterio.open(image_path) as src:
    # Image's metadata
    print('Metadata:', src.profile)
    # Image's bands
    print('Bands:', src.count)
    # Image's projection
    print('Projection:', src.crs)
    # Image's bounds
    print('Bounds:', src.bounds)

Because this image doesn't have a known projection, we'll do everything in the pixel reference system.

### Decomposing an Image

Open a geospatial image and reads the blue, green, and red bands as NumPy arrays.


In [ ]:
# Open the image and read the bands as numpy arrays
with rasterio.open(image_path) as src:
    blue = src.read(1)
    green = src.read(2)
    red = src.read(3)

Below helps give insight and understanding of the data we're dealing with:
- The luminance values of each pixel (how bright they are) in the blue band
- The image's radiometric resolution
- The minimum and maximum values of the luminance

In [11]:
# Print the blue band's data
print(blue)

# Print data type of the blue band
print('Data type:', blue.dtype)
print('Min:', blue.min())  #0
print('Max:', blue.max())  #2^8 - 1 = 255 (8-bit image)

[[ 91 101  85 ... 145 199 233]
 [ 97 102  82 ... 144 227 236]
 [ 90  92  90 ... 191 233 236]
 ...
 [216 195 108 ...  79  78  67]
 [203 158 118 ...  74  82  77]
 [142 151 150 ...  75  79  73]]
Data type: uint8
Min: 0
Max: 255


Use Matplotlib to visualize the red, green, and blue bands of the image.

In [ ]:
import matplotlib.pyplot as plt

fig = plt.figure(frameon=False)
ax = plt.Axes(fig, [0., 0., 1., 1.])
ax.set_axis_off()
fig.add_axes(ax)
ax.imshow(red, cmap='Reds')
plt.show()

fig = plt.figure(frameon=False)
ax = plt.Axes(fig, [0., 0., 1., 1.])
ax.set_axis_off()
fig.add_axes(ax)
ax.imshow(green, cmap='Greens')
plt.axis('off')
plt.show()

fig = plt.figure(frameon=False)
ax = plt.Axes(fig, [0., 0., 1., 1.])
ax.set_axis_off()
fig.add_axes(ax)
ax.imshow(blue, cmap='Blues')
plt.axis('off')
plt.show()

### Composing a Scene

Stack together the blue, green, and red bands to green a visual-band (RGB) image.

In [ ]:
import numpy as np

# Stack the bands to create a color image
rgb = np.dstack((blue, green, red))

print('RGB shape:', rgb.shape)

Visualize the RGB image.

In [ ]:
# Visualize the color image
fig = plt.figure(frameon=False)
ax = plt.Axes(fig, [0., 0., 1., 1.])
ax.set_axis_off()
fig.add_axes(ax)
ax.imshow(rgb)
plt.axis('off')
plt.show()